version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - HOLOGRAPHIC_USE_GPU=false
      - HOLOGRAPHIC_DATA_DIR=/app/.testdata
    command: bash -lc "pip install -U pip && pip install -e services/holographic-memory/core .[dev] && uvicorn services.holographic-memory.api.app_soa:app --host 0.0.0.0 --port 8081"
    ports:
      - "8081:8081"
    tmpfs:
      - /app/.testdata

