version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      - HOLO_ROOT=/data
      - GRID_SIZE=64
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"

