#!/bin/sh
#
# Recompile the .py files.
#

PYVER="3.12"
FWK="/Library/Frameworks/Python.framework/Versions/3.12"

"${FWK}/bin/python3.12" -E -s -Wi \
    "${FWK}/lib/python${PYVER}/compileall.py" -q -j0 \
    -f -x 'bad_coding|badsyntax|site-packages|test/test_lib2to3/data' \
    "${FWK}/lib/python${PYVER}"

"${FWK}/bin/python3.12" -E -s -Wi -O \
    "${FWK}/lib/python${PYVER}/compileall.py" -q -j0 \
    -f -x 'bad_coding|badsyntax|site-packages|test/test_lib2to3/data' \
    "${FWK}/lib/python${PYVER}"

"${FWK}/bin/python3.12" -E -s -Wi \
    "${FWK}/lib/python${PYVER}/compileall.py" -q -j0 \
    -f -x badsyntax \
    "${FWK}/lib/python${PYVER}/site-packages"

"${FWK}/bin/python3.12" -E -s -Wi -O \
    "${FWK}/lib/python${PYVER}/compileall.py" -q -j0 \
    -f -x badsyntax \
    "${FWK}/lib/python${PYVER}/site-packages"

chgrp -R admin "${FWK}"
chmod -R g+w "${FWK}"

exit 0
