name: Comprehensive Test Suite

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e services/holographic-memory/core
          pip install .[dev,enterprise]

      - name: Run full test matrix (unit+integration+monitoring)
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: |
          pytest -m "unit or integration or monitoring" -q

      - name: Security scans (non-blocking)
        continue-on-error: true
        run: |
          pytest -m security -q || true

      - name: Performance smoke (non-blocking)
        continue-on-error: true
        run: |
          pytest -m performance -q || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: comprehensive-test-reports
          path: |
            tests/reports/**

